# Generated by Django 3.2.23 on 2024-01-28 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_rejestracyjny', models.CharField(max_length=8, unique=True)),
                ('marka', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('rok_produkcji', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('kategoria', models.CharField(choices=[('suv', 'SUV'), ('osobowy', 'Osobowy'), ('sportowy', 'Sportowy')], max_length=20)),
                ('moc', models.IntegerField()),
                ('opis', models.TextField()),
                ('skrzynia', models.CharField(choices=[('automatyczna', 'Automatyczna'), ('manualna', 'Manualna')], max_length=20)),
                ('naped', models.CharField(choices=[('przod', 'Przód'), ('tyl', 'Tył'), ('4x4', '4x4')], max_length=10)),
                ('przyspieszenie', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pojemnosc', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('przebieg', models.IntegerField()),
                ('zdjecie1', models.ImageField(upload_to='img/')),
                ('zdjecie2', models.ImageField(upload_to='img/')),
                ('zdjecie3', models.ImageField(upload_to='img/')),
                ('zdjecie4', models.ImageField(upload_to='img/')),
                ('zdjecie5', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(null=True)),
                ('ilosc_dni', models.IntegerField(default=12)),
                ('status_wypozyczenia', models.CharField(choices=[('Rezerwacja', 'Rezerwacja'), ('Wypożyczenie', 'Wypożyczony'), ('Zakończony', 'Zakończone')], max_length=50)),
                ('czy_oplacone', models.BooleanField(default=False)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zarzadzanie_pojazdami.pojazd')),
            ],
        ),
    ]
