# Generated by Django 3.2.23 on 2024-01-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzanie_pojazdami', '0002_alter_wypozyczenie_ilosc_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wypozyczenie',
        ),
    ]
