# Generated by Django 3.2.23 on 2024-01-28 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zarzadzanie_pojazdami', '0003_delete_wypozyczenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(null=True)),
                ('ilosc_dni', models.IntegerField(default=1)),
                ('status_wypozyczenia', models.CharField(choices=[('Rezerwacja', 'Rezerwacja'), ('Wypożyczenie', 'Wypożyczony'), ('Zakończony', 'Zakończone')], max_length=50)),
                ('czy_oplacone', models.BooleanField(default=False)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zarzadzanie_pojazdami.pojazd')),
            ],
        ),
    ]
