# Generated by Django 3.2.23 on 2024-01-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzanie_pojazdami', '0004_wypozyczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenie',
            name='status_wypozyczenia',
            field=models.CharField(choices=[('Rezerwacja', 'Rezerwacja'), ('Wypożyczenie', 'Wypożyczony'), ('Zakończony', 'Zakończone')], default='Rezerwacja', max_length=50),
        ),
    ]
